### ISSUE TITLE
Rajouter une miniature de l'illustration pas fonctionnel

### ISSUE THREAD

**Issue by jpklipfel** [cigalsace/mdedit#1]
![image 5](https://cloud.githubusercontent.com/assets/5012040/10362323/3e867342-6dae-11e5-8ade-2db36511b4e7.png)

Testé sous FireFox 41.0.1

**Comment by gryckelynck** [comment]
Je ne reproduis pas le pb sous FF 41.0.1.
Est-ce que ça se produit à l'ouverture de l'application?
Peux-tu préciser l'action réalisée?
As-tu un message dans la console FF?

**Comment by jpklipfel** [comment]
Je ne reproduis plus l'erreur après rafraichissement de la page
