### ISSUE TITLE
lorsque le thème européen est renseigné, il devient impossible de générer le xml.

### ISSUE THREAD

**Issue by jpklipfel** [cigalsace/mdedit#25]
[SLM67] Je vous signale juste un petit bug dans MD Edit: lorsque le thème européen est renseigné, il devient impossible de générer le xml.

**Comment by gryckelynck** [comment]
Corrigé avec https://github.com/cigalsace/mdedit/commit/04871ebdb5527de6653040f83392c9ef125fbb99
et redéployé.
A tester

**Comment by jpklipfel** [comment]
[SLM67] Ca fonctionne bien, je vous remercie.
